#!/bin/sh

servers="root@nomadnt.com"
app_name="betsbrothers"
app_repo="$(git config --get remote.origin.url)"
app_branch="${1:-master}"
app_uri="/var/www/betsbrothers.com/betsbrothers.com"
# WEBHOOK_URL='https://hooks.slack.com/services/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';

for server in $servers; do ssh $server '/bin/sh -s' <<-ENDSSH
#!/bin/sh

[ -d $app_uri ] || {
    git clone $app_repo --branch=$app_branch $app_uri;
    cp $app_uri/src/.env.example $app_uri/src/.env
    touch $app_uri/src/database/database.sqlite
}

cd $app_uri;

[ \$(git rev-parse --abbrev-ref HEAD) = "$app_branch" ] || {    
    git fetch; git checkout .; git checkout $app_branch;    
}

git pull origin $app_branch;

composer install --quiet --prefer-dist --no-interaction -d src;

php src/artisan migrate --force --no-interaction;
php src/artisan cache:clear

chown -R www-data.www-data $app_uri
find $app_uri -type d -exec chmod 755 {} \;
find $app_uri -type f -exec chmod 644 {} \;

command -v supervisorctl >/dev/null 2>&1 && supervisorctl update $app_name

[ -z $WEBHOOK_URL ] || {
    curl -X POST -H 'Content-type: application/json' --data '{"text":"Deploy tasks ran on <{$app_uri}|{$app_name}>"}' $WEBHOOK_URL
}

ENDSSH
done